### ISSUE TITLE
ARM compatible docker image

### ISSUE THREAD

**Issue by nmapx** [dfoxg/kratos-admin-ui#159]
Hi @dfoxg
Do you plan to add `arm64` compatible docker image to public registry?
IMO it should be plug&play. I will be happy to help if you need anything.
Cheers!

**Comment by dfoxg** [comment]
It wasn't planned until now, but I will have a look at it :)
PRs are welcome 😛

**Comment by nmapx** [comment]
I can't find commands related to the release process.
I guess you do it manually (pushing images to `ghcr.io/dfoxg/kratos-admin-ui` registry?
So if you want to do it for x-platform you need to replace `docker build ...` command with `docker buildx`.
If never did it before you will probably need to create a new builder:
```bash
docker buildx create --use --platform=linux/arm64,linux/amd64 --name multi-platform-builder
```
Then build the image(s) based on the Dockerfile using following command (it will push the images to registry).
```bash
docker buildx build -t ghcr.io/dfoxg/kratos-admin-ui:latest --platform linux/amd64 --platform linux/arm64 --no-cache --pull --push .
```
The trick is - Docker won't display x-platform images on the list `docker images` - it will always show images dedicated for your current platform. By using `--push` we send those images to registry right away where it will be visible as a x-platform image.

**Comment by nmapx** [comment]
@dfoxg done, please check if it looks good to you

**Comment by dfoxg** [comment]
@nmapx hm still doesn't work. I will have a look at it later, I'm not at home right now :)

**Comment by nmapx** [comment]
@dfoxg published a fix after the last commit
env var wasn't properly used after moving from bash cmd to direct plugin usage

**Comment by nmapx** [comment]
I see, well CI/CD pipelines sucks when it comes to dry-run/debug 😓 
https://github.com/docker/build-push-action/issues/276 it's a similar use case for some reason the variable we are using here is not accessible/empty

**Comment by nmapx** [comment]
I suspect the release workflow might work fine because the variable is directly declared there
Look at the issue linked above
```yaml
...
            -
                name: What
                run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
...
                name: Build and push
                uses: docker/build-push-action@v2
                with:
                    context: ./docker
                    file: ./docker/Dockerfile
                    platforms: linux/amd64,linux/arm64,linux/386
                    push: true
                    tags: splitbrain/dokuwiki:${{ env.BRANCH }}
...
```
Maybe `GITHUB_SHA` is not accessible and we need to rewrite it in order to use it in the plugin?
