### ISSUE TITLE
Container takes long time to stop

### ISSUE THREAD

**Issue by robertsLando** [dfoxg/kratos-admin-ui#226]
Compose down actually takes 10s when all other containers take at most 1s.

Compose:

```yml
 kratos_admin_ui:
    image: ghcr.io/dfoxg/kratos-admin-ui:v2.5.0
    ports:
      - '9095:8080'
    restart: unless-stopped
    environment:
      KRATOS_ADMIN_URL: http://kratos:4434
      KRATOS_PUBLIC_URL: http://kratos:4433
```

![immagine](https://github.com/user-attachments/assets/3c695d26-b6d2-422c-b42f-93d84bf45838)
